version: 2
updates:
# Generates far too much PR noise
# - package-ecosystem: cargo
#   directory: "/"
#   schedule:
#     interval: monthly
#     time: "13:00"
#   open-pull-requests-limit: 10
#   commit-message:
#     prefix: "chore: "
#   allow:
#    - dependency-type: "direct"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
